### ISSUE TITLE
Add blockchain

### ISSUE THREAD

**Issue by fkrause98** [hixion/tiny-compiler#1]
Can we add blockchain to this project?
And also aidrop pls many thanks.

**Comment by Yhodhan** [comment]
> Can we add blockchain to this project? And also aidrop pls many thanks.

Hello, i think it will not be possible just yet as it exceeds the goals of the first milestone. Maybe in the future we can add some cardano and solana into it!

**Comment by fkrause98** [comment]
That's too bad :(
